# Development docker-compose for easier development
version: '3.8'

services:
  whatsapp-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: whatsapp-sessions-dev
    ports:
      - "3000:3000"
      - "1100:1100"  # Vite dev server
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_PORT=1100
      - WAAKU_RUNTIME=linux
      # Frontend uses origin by default; optionally set explicit base URL
      - VITE_API_BASE_URL=http://localhost:3000
      # API key config (client uses raw UUID4, server uses SHA-512 hash)
      # - VITE_API_KEY=${VITE_API_KEY}
      # - WAAKU_API_KEY=${WAAKU_API_KEY}
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reload
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # Persist WhatsApp session data
      - whatsapp_sessions_dev:/usr/src/app/.wwebjs_auth
    restart: unless-stopped
    shm_size: '1gb'
    networks:
      - whatsapp-network-dev
    command: npm run dev

volumes:
  whatsapp_sessions_dev:
    driver: local

networks:
  whatsapp-network-dev:
    driver: bridge
