version: '3.8'

services:
  waaku-app:
    image: waaku-app:latest
    build: .
    container_name: waaku
    env_file:
      - .env
    ports:
      - "1100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WAAKU_RUNTIME=linux
      # API key configuration (server expects SHA-512 hash)
      # Set WAAKU_API_KEY to sha512(raw_uuid_key_without_dashes)
      # e.g., WAAKU_API_KEY=ab12... (128 hex chars)
      # - WAAKU_API_KEY=${WAAKU_API_KEY}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      # Persist WhatsApp session data
      - whatsapp_sessions:/usr/src/app/.wwebjs_auth
      # Optionally mount logs
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    shm_size: '1gb'
    networks:
      - waaku-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: waaku-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - waaku-app
    restart: unless-stopped
    networks:
      - waaku-network
    profiles:
      - with-nginx

volumes:
  whatsapp_sessions:
    driver: local

networks:
  waaku-network:
    driver: bridge
