version: '3.8'

services:
  app:
    build:
      context: .
      args:
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_AUTH_USER: ${VITE_AUTH_USER}
        VITE_AUTH_PASS: ${VITE_AUTH_PASS}
    platform: linux/amd64
    container_name: waaku
    env_file:
      - .env
    ports:
      - "4300:4300"
    environment:
      NODE_ENV: production
      PORT: 4300
      # API key configuration (server expects SHA-512 hash)
      # Set WAAKU_API_KEY to sha512(raw_uuid_key_without_dashes)
      # e.g., WAAKU_API_KEY=ab12... (128 hex chars)
      FRONTEND_PORT: ${FRONTEND_PORT}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_API_KEY: ${VITE_API_KEY}
      WAAKU_API_KEY: ${WAAKU_API_KEY}
      WAAKU_RUNTIME: ${WAAKU_RUNTIME}
      VITE_AUTH_USER: ${VITE_AUTH_USER}
      VITE_AUTH_PASS: ${VITE_AUTH_PASS}
      VITE_API_DEV_PORT: ${VITE_API_DEV_PORT}
      VITE_SOCKET_PORT: ${VITE_SOCKET_PORT}
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    volumes:
      # Persist WhatsApp session data
      - whatsapp_sessions:/usr/src/app/.wwebjs_auth
      # Optionally mount logs
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    shm_size: '1gb'
    networks:
      - waaku-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4300"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: waaku-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - waaku-network
    profiles:
      - with-nginx

volumes:
  whatsapp_sessions:
    driver: local

networks:
  waaku-network:
    driver: bridge
