version: '3.8'

services:
  whatsapp-app:
    build: .
    container_name: whatsapp-sessions
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      # Persist WhatsApp session data
      - whatsapp_sessions:/usr/src/app/.wwebjs_auth
      # Optionally mount logs
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    shm_size: '1gb'
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - whatsapp-app
    restart: unless-stopped
    networks:
      - whatsapp-network
    profiles:
      - with-nginx

volumes:
  whatsapp_sessions:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
